name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  workflow_run:
    workflows: ["Add Movie to Database"]
    types:
      - completed

concurrency:
  group: movie-pipeline
  cancel-in-progress: false


permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout FS-Logic (UI & Data)
        uses: actions/checkout@v4
        with:
          repository: 'ThuVienC/FS-Logic'
          token: ${{ secrets.LOGIC_REPO_PAT }}
          path: 'ui-data'

      - name: Sync from MongoDB
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          DATABASE_FILE_PATH: 'movies.json'
        run: |
          cd ui-data
          npm install mongodb dotenv
          node scripts/sync_db.js

      - name: Prepare Deployment
        run: |
          mkdir build
          cp -r ui-data/* build/
          # movies.json đã được sync từ MongoDB ở bước trên
          # Xóa các file không cần thiết cho deploy
          rm -rf build/scripts
          rm -rf build/.git

      - name: Secure & Obfuscate JS
        run: |
          npm install -g javascript-obfuscator
          javascript-obfuscator ./build/assets/js --config ./ui-data/obfuscator-config.json --output ./build/assets/js

      - name: Minify HTML & CSS
        run: |
          npm install -g html-minifier-terser clean-css-cli
          # Nén HTML
          html-minifier-terser --input-dir ./build --output-dir ./build --collapse-whitespace --remove-comments --minify-js true --minify-css true --file-ext html
          # Nén CSS
          cleancss -o ./build/assets/css/main.css ./build/assets/css/main.css
          cleancss -o ./build/assets/css/style.css ./build/assets/css/style.css

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
